package org.l88.mos.um.domain;

import org.l88.mos.domain.user.Person;

public class UmbPerson extends Person{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMB_PERSON.PERSON_ID
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMB_PERSON.NAME
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMB_PERSON.EMPLOYEE_ID
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    private Long employeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMB_PERSON.GENDER
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMB_PERSON.BIRTH_DATE
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    private String birthDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMB_PERSON.MOBILE_NO
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    private String mobileNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMB_PERSON.COUNTRY_ALPHA_ID
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    private String countryAlphaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMB_PERSON.STATE_ID
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    private String stateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMB_PERSON.CITY_ID
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    private String cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMB_PERSON.HOME_ADDRESS1
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    private String homeAddress1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMB_PERSON.HOME_ADDRESS2
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    private String homeAddress2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMB_PERSON.HOME_TELPHONE
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    private String homeTelphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMB_PERSON.HOME_POST_CODE
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    private String homePostCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UMB_PERSON.EMAIL
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMB_PERSON.PERSON_ID
     *
     * @return the value of UMB_PERSON.PERSON_ID
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMB_PERSON.PERSON_ID
     *
     * @param id the value for UMB_PERSON.PERSON_ID
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMB_PERSON.NAME
     *
     * @return the value of UMB_PERSON.NAME
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMB_PERSON.NAME
     *
     * @param name the value for UMB_PERSON.NAME
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMB_PERSON.EMPLOYEE_ID
     *
     * @return the value of UMB_PERSON.EMPLOYEE_ID
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public Long getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMB_PERSON.EMPLOYEE_ID
     *
     * @param employeeId the value for UMB_PERSON.EMPLOYEE_ID
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public void setEmployeeId(Long employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMB_PERSON.GENDER
     *
     * @return the value of UMB_PERSON.GENDER
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMB_PERSON.GENDER
     *
     * @param gender the value for UMB_PERSON.GENDER
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMB_PERSON.BIRTH_DATE
     *
     * @return the value of UMB_PERSON.BIRTH_DATE
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public String getBirthDate() {
        return birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMB_PERSON.BIRTH_DATE
     *
     * @param birthDate the value for UMB_PERSON.BIRTH_DATE
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public void setBirthDate(String birthDate) {
        this.birthDate = birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMB_PERSON.MOBILE_NO
     *
     * @return the value of UMB_PERSON.MOBILE_NO
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public String getMobileNo() {
        return mobileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMB_PERSON.MOBILE_NO
     *
     * @param mobileNo the value for UMB_PERSON.MOBILE_NO
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMB_PERSON.COUNTRY_ALPHA_ID
     *
     * @return the value of UMB_PERSON.COUNTRY_ALPHA_ID
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public String getCountryAlphaId() {
        return countryAlphaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMB_PERSON.COUNTRY_ALPHA_ID
     *
     * @param countryAlphaId the value for UMB_PERSON.COUNTRY_ALPHA_ID
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public void setCountryAlphaId(String countryAlphaId) {
        this.countryAlphaId = countryAlphaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMB_PERSON.STATE_ID
     *
     * @return the value of UMB_PERSON.STATE_ID
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public String getStateId() {
        return stateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMB_PERSON.STATE_ID
     *
     * @param stateId the value for UMB_PERSON.STATE_ID
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public void setStateId(String stateId) {
        this.stateId = stateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMB_PERSON.CITY_ID
     *
     * @return the value of UMB_PERSON.CITY_ID
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMB_PERSON.CITY_ID
     *
     * @param cityId the value for UMB_PERSON.CITY_ID
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public void setCityId(String cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMB_PERSON.HOME_ADDRESS1
     *
     * @return the value of UMB_PERSON.HOME_ADDRESS1
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public String getHomeAddress1() {
        return homeAddress1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMB_PERSON.HOME_ADDRESS1
     *
     * @param homeAddress1 the value for UMB_PERSON.HOME_ADDRESS1
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public void setHomeAddress1(String homeAddress1) {
        this.homeAddress1 = homeAddress1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMB_PERSON.HOME_ADDRESS2
     *
     * @return the value of UMB_PERSON.HOME_ADDRESS2
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public String getHomeAddress2() {
        return homeAddress2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMB_PERSON.HOME_ADDRESS2
     *
     * @param homeAddress2 the value for UMB_PERSON.HOME_ADDRESS2
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public void setHomeAddress2(String homeAddress2) {
        this.homeAddress2 = homeAddress2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMB_PERSON.HOME_TELPHONE
     *
     * @return the value of UMB_PERSON.HOME_TELPHONE
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public String getHomeTelphone() {
        return homeTelphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMB_PERSON.HOME_TELPHONE
     *
     * @param homeTelphone the value for UMB_PERSON.HOME_TELPHONE
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public void setHomeTelphone(String homeTelphone) {
        this.homeTelphone = homeTelphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMB_PERSON.HOME_POST_CODE
     *
     * @return the value of UMB_PERSON.HOME_POST_CODE
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public String getHomePostCode() {
        return homePostCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMB_PERSON.HOME_POST_CODE
     *
     * @param homePostCode the value for UMB_PERSON.HOME_POST_CODE
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public void setHomePostCode(String homePostCode) {
        this.homePostCode = homePostCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UMB_PERSON.EMAIL
     *
     * @return the value of UMB_PERSON.EMAIL
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UMB_PERSON.EMAIL
     *
     * @param email the value for UMB_PERSON.EMAIL
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

	@Override
	public String getHomeAddress() {
		return getHomeAddress1();
	}

	@Override
	public void setHomeAddress(String homeAddress) {
		setHomeAddress1(homeAddress);
	}
}