package org.l88.mos.um.domain;

import java.util.ArrayList;
import java.util.List;

public class UmbPersonExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UMB_PERSON
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UMB_PERSON
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table UMB_PERSON
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMB_PERSON
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public UmbPersonExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMB_PERSON
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMB_PERSON
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMB_PERSON
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMB_PERSON
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMB_PERSON
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMB_PERSON
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMB_PERSON
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMB_PERSON
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMB_PERSON
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMB_PERSON
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UMB_PERSON
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("PERSON_ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("PERSON_ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("PERSON_ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("PERSON_ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("PERSON_ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("PERSON_ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("PERSON_ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("PERSON_ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("PERSON_ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("PERSON_ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("PERSON_ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("PERSON_ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdIsNull() {
            addCriterion("EMPLOYEE_ID is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdIsNotNull() {
            addCriterion("EMPLOYEE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdEqualTo(Long value) {
            addCriterion("EMPLOYEE_ID =", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdNotEqualTo(Long value) {
            addCriterion("EMPLOYEE_ID <>", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdGreaterThan(Long value) {
            addCriterion("EMPLOYEE_ID >", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("EMPLOYEE_ID >=", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdLessThan(Long value) {
            addCriterion("EMPLOYEE_ID <", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdLessThanOrEqualTo(Long value) {
            addCriterion("EMPLOYEE_ID <=", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdIn(List<Long> values) {
            addCriterion("EMPLOYEE_ID in", values, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdNotIn(List<Long> values) {
            addCriterion("EMPLOYEE_ID not in", values, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdBetween(Long value1, Long value2) {
            addCriterion("EMPLOYEE_ID between", value1, value2, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdNotBetween(Long value1, Long value2) {
            addCriterion("EMPLOYEE_ID not between", value1, value2, "employeeId");
            return (Criteria) this;
        }

        public Criteria andGenderIsNull() {
            addCriterion("GENDER is null");
            return (Criteria) this;
        }

        public Criteria andGenderIsNotNull() {
            addCriterion("GENDER is not null");
            return (Criteria) this;
        }

        public Criteria andGenderEqualTo(String value) {
            addCriterion("GENDER =", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotEqualTo(String value) {
            addCriterion("GENDER <>", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThan(String value) {
            addCriterion("GENDER >", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThanOrEqualTo(String value) {
            addCriterion("GENDER >=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThan(String value) {
            addCriterion("GENDER <", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThanOrEqualTo(String value) {
            addCriterion("GENDER <=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLike(String value) {
            addCriterion("GENDER like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotLike(String value) {
            addCriterion("GENDER not like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderIn(List<String> values) {
            addCriterion("GENDER in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotIn(List<String> values) {
            addCriterion("GENDER not in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderBetween(String value1, String value2) {
            addCriterion("GENDER between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotBetween(String value1, String value2) {
            addCriterion("GENDER not between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andBirthDateIsNull() {
            addCriterion("BIRTH_DATE is null");
            return (Criteria) this;
        }

        public Criteria andBirthDateIsNotNull() {
            addCriterion("BIRTH_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andBirthDateEqualTo(String value) {
            addCriterion("BIRTH_DATE =", value, "birthDate");
            return (Criteria) this;
        }

        public Criteria andBirthDateNotEqualTo(String value) {
            addCriterion("BIRTH_DATE <>", value, "birthDate");
            return (Criteria) this;
        }

        public Criteria andBirthDateGreaterThan(String value) {
            addCriterion("BIRTH_DATE >", value, "birthDate");
            return (Criteria) this;
        }

        public Criteria andBirthDateGreaterThanOrEqualTo(String value) {
            addCriterion("BIRTH_DATE >=", value, "birthDate");
            return (Criteria) this;
        }

        public Criteria andBirthDateLessThan(String value) {
            addCriterion("BIRTH_DATE <", value, "birthDate");
            return (Criteria) this;
        }

        public Criteria andBirthDateLessThanOrEqualTo(String value) {
            addCriterion("BIRTH_DATE <=", value, "birthDate");
            return (Criteria) this;
        }

        public Criteria andBirthDateLike(String value) {
            addCriterion("BIRTH_DATE like", value, "birthDate");
            return (Criteria) this;
        }

        public Criteria andBirthDateNotLike(String value) {
            addCriterion("BIRTH_DATE not like", value, "birthDate");
            return (Criteria) this;
        }

        public Criteria andBirthDateIn(List<String> values) {
            addCriterion("BIRTH_DATE in", values, "birthDate");
            return (Criteria) this;
        }

        public Criteria andBirthDateNotIn(List<String> values) {
            addCriterion("BIRTH_DATE not in", values, "birthDate");
            return (Criteria) this;
        }

        public Criteria andBirthDateBetween(String value1, String value2) {
            addCriterion("BIRTH_DATE between", value1, value2, "birthDate");
            return (Criteria) this;
        }

        public Criteria andBirthDateNotBetween(String value1, String value2) {
            addCriterion("BIRTH_DATE not between", value1, value2, "birthDate");
            return (Criteria) this;
        }

        public Criteria andMobileNoIsNull() {
            addCriterion("MOBILE_NO is null");
            return (Criteria) this;
        }

        public Criteria andMobileNoIsNotNull() {
            addCriterion("MOBILE_NO is not null");
            return (Criteria) this;
        }

        public Criteria andMobileNoEqualTo(String value) {
            addCriterion("MOBILE_NO =", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoNotEqualTo(String value) {
            addCriterion("MOBILE_NO <>", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoGreaterThan(String value) {
            addCriterion("MOBILE_NO >", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoGreaterThanOrEqualTo(String value) {
            addCriterion("MOBILE_NO >=", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoLessThan(String value) {
            addCriterion("MOBILE_NO <", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoLessThanOrEqualTo(String value) {
            addCriterion("MOBILE_NO <=", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoLike(String value) {
            addCriterion("MOBILE_NO like", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoNotLike(String value) {
            addCriterion("MOBILE_NO not like", value, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoIn(List<String> values) {
            addCriterion("MOBILE_NO in", values, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoNotIn(List<String> values) {
            addCriterion("MOBILE_NO not in", values, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoBetween(String value1, String value2) {
            addCriterion("MOBILE_NO between", value1, value2, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andMobileNoNotBetween(String value1, String value2) {
            addCriterion("MOBILE_NO not between", value1, value2, "mobileNo");
            return (Criteria) this;
        }

        public Criteria andCountryAlphaIdIsNull() {
            addCriterion("COUNTRY_ALPHA_ID is null");
            return (Criteria) this;
        }

        public Criteria andCountryAlphaIdIsNotNull() {
            addCriterion("COUNTRY_ALPHA_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCountryAlphaIdEqualTo(String value) {
            addCriterion("COUNTRY_ALPHA_ID =", value, "countryAlphaId");
            return (Criteria) this;
        }

        public Criteria andCountryAlphaIdNotEqualTo(String value) {
            addCriterion("COUNTRY_ALPHA_ID <>", value, "countryAlphaId");
            return (Criteria) this;
        }

        public Criteria andCountryAlphaIdGreaterThan(String value) {
            addCriterion("COUNTRY_ALPHA_ID >", value, "countryAlphaId");
            return (Criteria) this;
        }

        public Criteria andCountryAlphaIdGreaterThanOrEqualTo(String value) {
            addCriterion("COUNTRY_ALPHA_ID >=", value, "countryAlphaId");
            return (Criteria) this;
        }

        public Criteria andCountryAlphaIdLessThan(String value) {
            addCriterion("COUNTRY_ALPHA_ID <", value, "countryAlphaId");
            return (Criteria) this;
        }

        public Criteria andCountryAlphaIdLessThanOrEqualTo(String value) {
            addCriterion("COUNTRY_ALPHA_ID <=", value, "countryAlphaId");
            return (Criteria) this;
        }

        public Criteria andCountryAlphaIdLike(String value) {
            addCriterion("COUNTRY_ALPHA_ID like", value, "countryAlphaId");
            return (Criteria) this;
        }

        public Criteria andCountryAlphaIdNotLike(String value) {
            addCriterion("COUNTRY_ALPHA_ID not like", value, "countryAlphaId");
            return (Criteria) this;
        }

        public Criteria andCountryAlphaIdIn(List<String> values) {
            addCriterion("COUNTRY_ALPHA_ID in", values, "countryAlphaId");
            return (Criteria) this;
        }

        public Criteria andCountryAlphaIdNotIn(List<String> values) {
            addCriterion("COUNTRY_ALPHA_ID not in", values, "countryAlphaId");
            return (Criteria) this;
        }

        public Criteria andCountryAlphaIdBetween(String value1, String value2) {
            addCriterion("COUNTRY_ALPHA_ID between", value1, value2, "countryAlphaId");
            return (Criteria) this;
        }

        public Criteria andCountryAlphaIdNotBetween(String value1, String value2) {
            addCriterion("COUNTRY_ALPHA_ID not between", value1, value2, "countryAlphaId");
            return (Criteria) this;
        }

        public Criteria andStateIdIsNull() {
            addCriterion("STATE_ID is null");
            return (Criteria) this;
        }

        public Criteria andStateIdIsNotNull() {
            addCriterion("STATE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andStateIdEqualTo(String value) {
            addCriterion("STATE_ID =", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdNotEqualTo(String value) {
            addCriterion("STATE_ID <>", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdGreaterThan(String value) {
            addCriterion("STATE_ID >", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdGreaterThanOrEqualTo(String value) {
            addCriterion("STATE_ID >=", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdLessThan(String value) {
            addCriterion("STATE_ID <", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdLessThanOrEqualTo(String value) {
            addCriterion("STATE_ID <=", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdLike(String value) {
            addCriterion("STATE_ID like", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdNotLike(String value) {
            addCriterion("STATE_ID not like", value, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdIn(List<String> values) {
            addCriterion("STATE_ID in", values, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdNotIn(List<String> values) {
            addCriterion("STATE_ID not in", values, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdBetween(String value1, String value2) {
            addCriterion("STATE_ID between", value1, value2, "stateId");
            return (Criteria) this;
        }

        public Criteria andStateIdNotBetween(String value1, String value2) {
            addCriterion("STATE_ID not between", value1, value2, "stateId");
            return (Criteria) this;
        }

        public Criteria andCityIdIsNull() {
            addCriterion("CITY_ID is null");
            return (Criteria) this;
        }

        public Criteria andCityIdIsNotNull() {
            addCriterion("CITY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCityIdEqualTo(String value) {
            addCriterion("CITY_ID =", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotEqualTo(String value) {
            addCriterion("CITY_ID <>", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdGreaterThan(String value) {
            addCriterion("CITY_ID >", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdGreaterThanOrEqualTo(String value) {
            addCriterion("CITY_ID >=", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLessThan(String value) {
            addCriterion("CITY_ID <", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLessThanOrEqualTo(String value) {
            addCriterion("CITY_ID <=", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLike(String value) {
            addCriterion("CITY_ID like", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotLike(String value) {
            addCriterion("CITY_ID not like", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdIn(List<String> values) {
            addCriterion("CITY_ID in", values, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotIn(List<String> values) {
            addCriterion("CITY_ID not in", values, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdBetween(String value1, String value2) {
            addCriterion("CITY_ID between", value1, value2, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotBetween(String value1, String value2) {
            addCriterion("CITY_ID not between", value1, value2, "cityId");
            return (Criteria) this;
        }

        public Criteria andHomeAddress1IsNull() {
            addCriterion("HOME_ADDRESS1 is null");
            return (Criteria) this;
        }

        public Criteria andHomeAddress1IsNotNull() {
            addCriterion("HOME_ADDRESS1 is not null");
            return (Criteria) this;
        }

        public Criteria andHomeAddress1EqualTo(String value) {
            addCriterion("HOME_ADDRESS1 =", value, "homeAddress1");
            return (Criteria) this;
        }

        public Criteria andHomeAddress1NotEqualTo(String value) {
            addCriterion("HOME_ADDRESS1 <>", value, "homeAddress1");
            return (Criteria) this;
        }

        public Criteria andHomeAddress1GreaterThan(String value) {
            addCriterion("HOME_ADDRESS1 >", value, "homeAddress1");
            return (Criteria) this;
        }

        public Criteria andHomeAddress1GreaterThanOrEqualTo(String value) {
            addCriterion("HOME_ADDRESS1 >=", value, "homeAddress1");
            return (Criteria) this;
        }

        public Criteria andHomeAddress1LessThan(String value) {
            addCriterion("HOME_ADDRESS1 <", value, "homeAddress1");
            return (Criteria) this;
        }

        public Criteria andHomeAddress1LessThanOrEqualTo(String value) {
            addCriterion("HOME_ADDRESS1 <=", value, "homeAddress1");
            return (Criteria) this;
        }

        public Criteria andHomeAddress1Like(String value) {
            addCriterion("HOME_ADDRESS1 like", value, "homeAddress1");
            return (Criteria) this;
        }

        public Criteria andHomeAddress1NotLike(String value) {
            addCriterion("HOME_ADDRESS1 not like", value, "homeAddress1");
            return (Criteria) this;
        }

        public Criteria andHomeAddress1In(List<String> values) {
            addCriterion("HOME_ADDRESS1 in", values, "homeAddress1");
            return (Criteria) this;
        }

        public Criteria andHomeAddress1NotIn(List<String> values) {
            addCriterion("HOME_ADDRESS1 not in", values, "homeAddress1");
            return (Criteria) this;
        }

        public Criteria andHomeAddress1Between(String value1, String value2) {
            addCriterion("HOME_ADDRESS1 between", value1, value2, "homeAddress1");
            return (Criteria) this;
        }

        public Criteria andHomeAddress1NotBetween(String value1, String value2) {
            addCriterion("HOME_ADDRESS1 not between", value1, value2, "homeAddress1");
            return (Criteria) this;
        }

        public Criteria andHomeAddress2IsNull() {
            addCriterion("HOME_ADDRESS2 is null");
            return (Criteria) this;
        }

        public Criteria andHomeAddress2IsNotNull() {
            addCriterion("HOME_ADDRESS2 is not null");
            return (Criteria) this;
        }

        public Criteria andHomeAddress2EqualTo(String value) {
            addCriterion("HOME_ADDRESS2 =", value, "homeAddress2");
            return (Criteria) this;
        }

        public Criteria andHomeAddress2NotEqualTo(String value) {
            addCriterion("HOME_ADDRESS2 <>", value, "homeAddress2");
            return (Criteria) this;
        }

        public Criteria andHomeAddress2GreaterThan(String value) {
            addCriterion("HOME_ADDRESS2 >", value, "homeAddress2");
            return (Criteria) this;
        }

        public Criteria andHomeAddress2GreaterThanOrEqualTo(String value) {
            addCriterion("HOME_ADDRESS2 >=", value, "homeAddress2");
            return (Criteria) this;
        }

        public Criteria andHomeAddress2LessThan(String value) {
            addCriterion("HOME_ADDRESS2 <", value, "homeAddress2");
            return (Criteria) this;
        }

        public Criteria andHomeAddress2LessThanOrEqualTo(String value) {
            addCriterion("HOME_ADDRESS2 <=", value, "homeAddress2");
            return (Criteria) this;
        }

        public Criteria andHomeAddress2Like(String value) {
            addCriterion("HOME_ADDRESS2 like", value, "homeAddress2");
            return (Criteria) this;
        }

        public Criteria andHomeAddress2NotLike(String value) {
            addCriterion("HOME_ADDRESS2 not like", value, "homeAddress2");
            return (Criteria) this;
        }

        public Criteria andHomeAddress2In(List<String> values) {
            addCriterion("HOME_ADDRESS2 in", values, "homeAddress2");
            return (Criteria) this;
        }

        public Criteria andHomeAddress2NotIn(List<String> values) {
            addCriterion("HOME_ADDRESS2 not in", values, "homeAddress2");
            return (Criteria) this;
        }

        public Criteria andHomeAddress2Between(String value1, String value2) {
            addCriterion("HOME_ADDRESS2 between", value1, value2, "homeAddress2");
            return (Criteria) this;
        }

        public Criteria andHomeAddress2NotBetween(String value1, String value2) {
            addCriterion("HOME_ADDRESS2 not between", value1, value2, "homeAddress2");
            return (Criteria) this;
        }

        public Criteria andHomeTelphoneIsNull() {
            addCriterion("HOME_TELPHONE is null");
            return (Criteria) this;
        }

        public Criteria andHomeTelphoneIsNotNull() {
            addCriterion("HOME_TELPHONE is not null");
            return (Criteria) this;
        }

        public Criteria andHomeTelphoneEqualTo(String value) {
            addCriterion("HOME_TELPHONE =", value, "homeTelphone");
            return (Criteria) this;
        }

        public Criteria andHomeTelphoneNotEqualTo(String value) {
            addCriterion("HOME_TELPHONE <>", value, "homeTelphone");
            return (Criteria) this;
        }

        public Criteria andHomeTelphoneGreaterThan(String value) {
            addCriterion("HOME_TELPHONE >", value, "homeTelphone");
            return (Criteria) this;
        }

        public Criteria andHomeTelphoneGreaterThanOrEqualTo(String value) {
            addCriterion("HOME_TELPHONE >=", value, "homeTelphone");
            return (Criteria) this;
        }

        public Criteria andHomeTelphoneLessThan(String value) {
            addCriterion("HOME_TELPHONE <", value, "homeTelphone");
            return (Criteria) this;
        }

        public Criteria andHomeTelphoneLessThanOrEqualTo(String value) {
            addCriterion("HOME_TELPHONE <=", value, "homeTelphone");
            return (Criteria) this;
        }

        public Criteria andHomeTelphoneLike(String value) {
            addCriterion("HOME_TELPHONE like", value, "homeTelphone");
            return (Criteria) this;
        }

        public Criteria andHomeTelphoneNotLike(String value) {
            addCriterion("HOME_TELPHONE not like", value, "homeTelphone");
            return (Criteria) this;
        }

        public Criteria andHomeTelphoneIn(List<String> values) {
            addCriterion("HOME_TELPHONE in", values, "homeTelphone");
            return (Criteria) this;
        }

        public Criteria andHomeTelphoneNotIn(List<String> values) {
            addCriterion("HOME_TELPHONE not in", values, "homeTelphone");
            return (Criteria) this;
        }

        public Criteria andHomeTelphoneBetween(String value1, String value2) {
            addCriterion("HOME_TELPHONE between", value1, value2, "homeTelphone");
            return (Criteria) this;
        }

        public Criteria andHomeTelphoneNotBetween(String value1, String value2) {
            addCriterion("HOME_TELPHONE not between", value1, value2, "homeTelphone");
            return (Criteria) this;
        }

        public Criteria andHomePostCodeIsNull() {
            addCriterion("HOME_POST_CODE is null");
            return (Criteria) this;
        }

        public Criteria andHomePostCodeIsNotNull() {
            addCriterion("HOME_POST_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andHomePostCodeEqualTo(String value) {
            addCriterion("HOME_POST_CODE =", value, "homePostCode");
            return (Criteria) this;
        }

        public Criteria andHomePostCodeNotEqualTo(String value) {
            addCriterion("HOME_POST_CODE <>", value, "homePostCode");
            return (Criteria) this;
        }

        public Criteria andHomePostCodeGreaterThan(String value) {
            addCriterion("HOME_POST_CODE >", value, "homePostCode");
            return (Criteria) this;
        }

        public Criteria andHomePostCodeGreaterThanOrEqualTo(String value) {
            addCriterion("HOME_POST_CODE >=", value, "homePostCode");
            return (Criteria) this;
        }

        public Criteria andHomePostCodeLessThan(String value) {
            addCriterion("HOME_POST_CODE <", value, "homePostCode");
            return (Criteria) this;
        }

        public Criteria andHomePostCodeLessThanOrEqualTo(String value) {
            addCriterion("HOME_POST_CODE <=", value, "homePostCode");
            return (Criteria) this;
        }

        public Criteria andHomePostCodeLike(String value) {
            addCriterion("HOME_POST_CODE like", value, "homePostCode");
            return (Criteria) this;
        }

        public Criteria andHomePostCodeNotLike(String value) {
            addCriterion("HOME_POST_CODE not like", value, "homePostCode");
            return (Criteria) this;
        }

        public Criteria andHomePostCodeIn(List<String> values) {
            addCriterion("HOME_POST_CODE in", values, "homePostCode");
            return (Criteria) this;
        }

        public Criteria andHomePostCodeNotIn(List<String> values) {
            addCriterion("HOME_POST_CODE not in", values, "homePostCode");
            return (Criteria) this;
        }

        public Criteria andHomePostCodeBetween(String value1, String value2) {
            addCriterion("HOME_POST_CODE between", value1, value2, "homePostCode");
            return (Criteria) this;
        }

        public Criteria andHomePostCodeNotBetween(String value1, String value2) {
            addCriterion("HOME_POST_CODE not between", value1, value2, "homePostCode");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("EMAIL =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("EMAIL <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("EMAIL >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("EMAIL <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("EMAIL <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("EMAIL like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("EMAIL not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("EMAIL in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("EMAIL not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("EMAIL between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("EMAIL not between", value1, value2, "email");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UMB_PERSON
     *
     * @mbggenerated do_not_delete_during_merge Sat Apr 30 19:34:33 HKT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table UMB_PERSON
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}