package org.l88.mos.um.dao;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.l88.mos.um.domain.UmbPerson;
import org.l88.mos.um.domain.UmbPersonExample;

public interface UmbPersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMB_PERSON
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    int countByExample(UmbPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMB_PERSON
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    int deleteByExample(UmbPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMB_PERSON
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    @Delete({
        "delete from UMB_PERSON",
        "where PERSON_ID = #{id,jdbcType=NUMERIC}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMB_PERSON
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    @Insert({
        "insert into UMB_PERSON (PERSON_ID, NAME, ",
        "EMPLOYEE_ID, GENDER, ",
        "BIRTH_DATE, MOBILE_NO, ",
        "COUNTRY_ALPHA_ID, STATE_ID, ",
        "CITY_ID, HOME_ADDRESS1, ",
        "HOME_ADDRESS2, HOME_TELPHONE, ",
        "HOME_POST_CODE, EMAIL)",
        "values (#{id,jdbcType=NUMERIC}, #{name,jdbcType=VARCHAR}, ",
        "#{employeeId,jdbcType=NUMERIC}, #{gender,jdbcType=CHAR}, ",
        "#{birthDate,jdbcType=CHAR}, #{mobileNo,jdbcType=VARCHAR}, ",
        "#{countryAlphaId,jdbcType=VARCHAR}, #{stateId,jdbcType=VARCHAR}, ",
        "#{cityId,jdbcType=VARCHAR}, #{homeAddress1,jdbcType=VARCHAR}, ",
        "#{homeAddress2,jdbcType=VARCHAR}, #{homeTelphone,jdbcType=VARCHAR}, ",
        "#{homePostCode,jdbcType=VARCHAR}, #{email,jdbcType=VARCHAR})"
    })
    @SelectKey(before = true, keyProperty = "id", keyColumn = "person_id", resultType = Long.class, 
	statement = "select max(persion_id)+1 from umb_person")
    int insert(UmbPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMB_PERSON
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    int insertSelective(UmbPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMB_PERSON
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    List<UmbPerson> selectByExample(UmbPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMB_PERSON
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    @Select({
        "select",
        "PERSON_ID, NAME, EMPLOYEE_ID, GENDER, BIRTH_DATE, MOBILE_NO, COUNTRY_ALPHA_ID, ",
        "STATE_ID, CITY_ID, HOME_ADDRESS1, HOME_ADDRESS2, HOME_TELPHONE, HOME_POST_CODE, ",
        "EMAIL",
        "from UMB_PERSON",
        "where PERSON_ID = #{id,jdbcType=NUMERIC}"
    })
    @ResultMap("BaseResultMap")
    UmbPerson selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMB_PERSON
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    int updateByExampleSelective(@Param("record") UmbPerson record, @Param("example") UmbPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMB_PERSON
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    int updateByExample(@Param("record") UmbPerson record, @Param("example") UmbPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMB_PERSON
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    int updateByPrimaryKeySelective(UmbPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UMB_PERSON
     *
     * @mbggenerated Sat Apr 30 19:34:33 HKT 2016
     */
    @Update({
        "update UMB_PERSON",
        "set NAME = #{name,jdbcType=VARCHAR},",
          "EMPLOYEE_ID = #{employeeId,jdbcType=NUMERIC},",
          "GENDER = #{gender,jdbcType=CHAR},",
          "BIRTH_DATE = #{birthDate,jdbcType=CHAR},",
          "MOBILE_NO = #{mobileNo,jdbcType=VARCHAR},",
          "COUNTRY_ALPHA_ID = #{countryAlphaId,jdbcType=VARCHAR},",
          "STATE_ID = #{stateId,jdbcType=VARCHAR},",
          "CITY_ID = #{cityId,jdbcType=VARCHAR},",
          "HOME_ADDRESS1 = #{homeAddress1,jdbcType=VARCHAR},",
          "HOME_ADDRESS2 = #{homeAddress2,jdbcType=VARCHAR},",
          "HOME_TELPHONE = #{homeTelphone,jdbcType=VARCHAR},",
          "HOME_POST_CODE = #{homePostCode,jdbcType=VARCHAR},",
          "EMAIL = #{email,jdbcType=VARCHAR}",
        "where PERSON_ID = #{id,jdbcType=NUMERIC}"
    })
    int updateByPrimaryKey(UmbPerson record);
}